# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job_a:
    runs-on: ubuntu-latest
    outputs:
      MY_VAR: ${{ steps.setOutput.outputs.MY_VAR }}
    steps:
      - name: Set output variable
        id: setOutput
        run: |
          echo "MY_VAR=Hello from Job A" >> $GITHUB_OUTPUT
          echo "The branch name is: ${{ variables['Build.SourceBranchName'] }}"

  job_b:
    runs-on: ubuntu-latest
    needs: job_a
    env:
      MY_VAR: ${{needs.job_a.outputs.MY_VAR}}
    steps:
      - name: Use output variable from job_a
        run: |
          echo "Okay : $MY_VAR"

